### ISSUE TITLE
[Feature request] llvm18

### ISSUE THREAD

**Issue by pkrause1980** [flathub/org.freedesktop.Sdk.Extension.llvm17#5]
I took a glimpse at the docs and could not see any dangerous change.

stage1 builds without any problems. It works too, tested by trivially modifying enable.sh / cleanup.

The "llvm" module does not build. The patches do not apply.
From the reject files, I guess someone familiar with the patches can fix it in minutes.
Unluckily, I'm not such a person and cannot spend the time in the near future.

Thanks!

**Comment by Erick555** [comment]
I plan to make in in coming days, please wait a bit more.

**Comment by Erick555** [comment]
submitted at https://github.com/flathub/flathub/pull/5140

**Comment by Erick555** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18
